### ISSUE TITLE
Un-handled exception

### ISSUE THREAD

**Issue by tygriffin** [dmonagle/elasticsearch-foundation-swift#1]
On line 120 of ESTransport.swift, `response` may be nil so the force downcast triggers an un-handled exception and prevents further retries. `let response = response as! HTTPURLResponse` can be moved into the else when error is nil.

**Comment by dmonagle** [comment]
Can you let me know how you managed to trigger this so I can make a test? The problem is that it doesn't check if response is nil. Testing with an invalid endpoint gives both an error and a response so it's not causing the exception you are seeing.
