### ISSUE TITLE
GET request with request body

### ISSUE THREAD

**Issue by tygriffin** [dmonagle/elasticsearch-foundation-swift#2]
The underlying implementation that performs the request in the ElasticsearchFoundation transport layer does not like GET requests with a request body. It might be worth throwing back a friendly error when using a GET request with a body, since Elasticsearch users would likely do that.

**Comment by dmonagle** [comment]
This appears to be an issue in Foundation when sending a request body along with a GET request. For the time being, as per the Elasticsearch recommendation, I've had the Transport automatically change GET to POST if the request has a httpBody
